FROM golang:alpine

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon \
    --directory=. \
    --exclude-dir=.git \
    --exclude-dir=.github \
    --exclude-dir=.postgres \
    --exclude-dir=node_modules \
    --build="./build/package/install.sh" \
    --command=serve --pattern="(.+\.go|.+\.c|.+\.html)$"
